server:
  port: 9100
spring:
  application:
    name: order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.6.35:8441,172.16.6.36:8442,172.16.6.41:8443

logging:
  level:
    com.liqihua.demo.service.OrderFeignApi: debug




