server:
  port: 8888
  servlet:
    context-path: /myOrder
spring:
  application:
    name: order-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.6.35:8841,172.16.6.36:8842,172.16.6.41:8843


